target_sources(Standard PRIVATE 
	Algorithm.h
	Aliases.h
	BaseManager.cpp
	BaseManager.h
	CompressedPair.h
	IManagerFactory.h
	Manager.h
	ManagerFactory.h
	Math/Angle.h
	Math/Real.h
	Math/Transform.cpp
	Math/Transform.h
	Pointers/BasePtr.h
	Pointers/Comparisons.h
	Pointers/EnableSharedFromThis.h
	Pointers/IsThronePtr.h
	Pointers/MakeFunctions.h
	Pointers/NotifiedPtr.h
	Pointers/PtrOwner.h
	Pointers/SharedPtr.h
	Pointers/WeakPtr.h
	Pointers/WeakPtr.hpp
	Pointers.h
	Private/Resource.h
	Private/TaskFence.h
	Task.h
	TypeTraits.h
)