target_sources(Core PRIVATE 
	BaseComponent.cpp
	BaseComponent.h
	Component.h
	ComponentTypeTraits/ComponentTypeTrait.cpp
	ComponentTypeTraits/ComponentTypeTrait.h
	ComponentTypeTraits/Dependencies.cpp
	ComponentTypeTraits/Dependencies.h
	Entity.cpp
	Entity.h
	EventProcessor.cpp
	EventProcessor.h
	ISystem.h
	ISystemFactory.h
	ManagerList.cpp
	ManagerList.h
	Math/Angle.h
	Math/Transform.cpp
	Math/Transform.h
	SharedComponent.cpp
	SharedComponent.h
	System.h
	SystemFactory.h
)